### ISSUE TITLE
position of in/out movment, opening more than two groups at a time

### ISSUE THREAD

**Issue by AlexanderKeynes** [null2/globalmigration#25]
Hello all,

I've been working on a project with Edouard Legoupil and have two queries. I'm new to this software so am not sure whether what I want is possible but thought it is worth asking!

Firstly, when myself and my boss looked at the visualizations, we both initially thought that emigration was marked but the inner ring (i.e. the layer removed from the outer circle) and immigration marked by the outer ring (i.e. the layer touching the outer circle) but after a minute realised that we'd both made the same mistake and it was actually the other way around. We're wondering whether it would be possible to flip the two around as we feel that would be more intuitive.

Secondly, at the moment we are limited to opening only two sections at a time and when you open a third one of the others automatically closes. I understand that this is to ensure that the user is not overloaded with information but our groupings only have four different sub-sections each and so it would be useful if we could open them all at the same time.

Thanks for your help in advance!

**Comment by espinielli** [comment]
The code is well written and you can happily define your config options in order to implemente what you asked for.

In order to invert the size of the gap for the in/out flows simply pass your own [config preferences for the gaps](https://github.com/null2/globalmigration/blob/master/lib/chart.js#L29-L30) instead of the default ones.

To have more than 2 regions open at the same time, again, use [the relevant config option](https://github.com/null2/globalmigration/blob/master/lib/chart.js#L48).

An example of [how to pass options different from the default is in the `index.html` file](https://github.com/null2/globalmigration/blob/master/index.html#L245-L255)

**Comment by argl** [comment]
thanks for taking the time to shed a light on this.
